/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    forceSwcTransforms: true,
  },
  transpilePackages: [
    "@bgo/sdk",
    "@bgo/sdk-client",
    "@bgo/contracts",
    "@bgo/games-avalon",
    "@bgo/games-battleship",
    "@bgo/games-checkers",
    "@bgo/games-chess",
    "@bgo/games-codenames",
    "@bgo/games-connectfour",
    "@bgo/games-coup",
    "@bgo/games-dotsandboxes",
    "@bgo/games-forsale",
    "@bgo/games-gomoku",
    "@bgo/games-hanabi",
    "@bgo/games-hearts",
    "@bgo/games-liarsdice",
    "@bgo/games-loveletter",
    "@bgo/games-mancala",
    "@bgo/games-mastermind",
    "@bgo/games-memory",
    "@bgo/games-nim",
    "@bgo/games-nothanks",
    "@bgo/games-pentago",
    "@bgo/games-quoridor",
    "@bgo/games-reversi",
    "@bgo/games-rps",
    "@bgo/games-secrethitler",
    "@bgo/games-skull",
    "@bgo/games-splendor",
    "@bgo/games-spyfall",
    "@bgo/games-sushigo",
    "@bgo/games-tictactoe",
    "@bgo/games-yahtzee",
  ],
};

module.exports = nextConfig;
