"use client";

import { registerClientModule } from "@bgo/sdk-client";
import { ticTacToeClientModule } from "@bgo/games-tictactoe/client";
import { connectFourClientModule } from "@bgo/games-connectfour/client";
import { codenamesClientModule } from "@bgo/games-codenames/client";
import { spyfallClientModule } from "@bgo/games-spyfall/client";
import { reversiClientModule } from "@bgo/games-reversi/client";
import { checkersClientModule } from "@bgo/games-checkers/client";
import { chessClientModule } from "@bgo/games-chess/client";
import { gomokuClientModule } from "@bgo/games-gomoku/client";
import { dotsAndBoxesClientModule } from "@bgo/games-dotsandboxes/client";
import { battleshipClientModule } from "@bgo/games-battleship/client";
import { mastermindClientModule } from "@bgo/games-mastermind/client";
import { nimClientModule } from "@bgo/games-nim/client";
import { rpsClientModule } from "@bgo/games-rps/client";
import { memoryClientModule } from "@bgo/games-memory/client";
import { heartsClientModule } from "@bgo/games-hearts/client";
import { mancalaClientModule } from "@bgo/games-mancala/client";
import { liarsDiceClientModule } from "@bgo/games-liarsdice/client";
import { yahtzeeClientModule } from "@bgo/games-yahtzee/client";
import { avalonClientModule } from "@bgo/games-avalon/client";
import { coupClientModule } from "@bgo/games-coup/client";
import { loveLetterClientModule } from "@bgo/games-loveletter/client";
import { secretHitlerClientModule } from "@bgo/games-secrethitler/client";
import { skullClientModule } from "@bgo/games-skull/client";
import { quoridorClientModule } from "@bgo/games-quoridor/client";
import { forSaleClientModule } from "@bgo/games-forsale/client";
import { splendorClientModule } from "@bgo/games-splendor/client";
import { noThanksClientModule } from "@bgo/games-nothanks/client";
import { pentagoClientModule } from "@bgo/games-pentago/client";
import { sushiGoClientModule } from "@bgo/games-sushigo/client";
import { hanabiClientModule } from "@bgo/games-hanabi/client";
import { bloodClocktowerClientModule } from "@bgo/games-bloodclocktower/client";

let registered = false;

/** Idempotent — safe to call from any client entry point. */
export function registerAllClientGames(): void {
  if (registered) return;
  registerClientModule(ticTacToeClientModule);
  registerClientModule(connectFourClientModule);
  registerClientModule(codenamesClientModule);
  registerClientModule(spyfallClientModule);
  registerClientModule(reversiClientModule);
  registerClientModule(checkersClientModule);
  registerClientModule(chessClientModule);
  registerClientModule(gomokuClientModule);
  registerClientModule(dotsAndBoxesClientModule);
  registerClientModule(battleshipClientModule);
  registerClientModule(mastermindClientModule);
  registerClientModule(nimClientModule);
  registerClientModule(rpsClientModule);
  registerClientModule(memoryClientModule);
  registerClientModule(heartsClientModule);
  registerClientModule(mancalaClientModule);
  registerClientModule(liarsDiceClientModule);
  registerClientModule(yahtzeeClientModule);
  registerClientModule(avalonClientModule);
  registerClientModule(coupClientModule);
  registerClientModule(loveLetterClientModule);
  registerClientModule(secretHitlerClientModule);
  registerClientModule(skullClientModule);
  registerClientModule(quoridorClientModule);
  registerClientModule(forSaleClientModule);
  registerClientModule(splendorClientModule);
  registerClientModule(noThanksClientModule);
  registerClientModule(pentagoClientModule);
  registerClientModule(sushiGoClientModule);
  registerClientModule(hanabiClientModule);
  registerClientModule(bloodClocktowerClientModule);
  registered = true;
}
